platform :ios, '8.0'

project 'AccountKitSwiftSample', 'Application' => :debug, 'Application' => :release

target 'AccountKitSwiftSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AccountKit'

end
